"use client"
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { IoHomeOutline } from "react-icons/io5";
import Navbar from "./components/Navbar";
import { useState } from "react";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [open, setOpen] = useState<any>();

  return (
    <html lang="en">
      <body>
        <div className="z-50 bg-custom-blue-200 md:hidden fixed flex flex-col gap-2 justify-between w-full px-5 py-2">
          <div className="flex gap-2 items-start">
            <i className="bg-blue-400 text-white rounded-full p-2 text-xl"><IoHomeOutline /></i>
            <h2 className='text-xl flex font-semibold pt-1 text-white'>Finloans</h2>
          </div>
          <button onClick={() => { setOpen(true) }} className='bg-gray-400 px-8 text-lg text-white py-2 font-medium rounded-md'>MENU</button>
          {open ? (
            <ul className="flex flex-col gap-5 text-white pt-3">
              <div className="flex justify-end right-0 top-0">
                <button onClick={() => { setOpen(false) }} className='bg-red-600 right- px-4 py-2 text-xl text-white font-medium rounded-full'>*</button>
              </div>

              <a href="/">         <li className="hover:text-custom-cyan">Home</li>     </a>
              <a href="/loan">      <li className="hover:text-custom-cyan">Loan</li>     </a>
              <a href="/about">     <li className="hover:text-custom-cyan">About</li>    </a>
              <a href="#">          <li className="hover:text-custom-cyan">Pages</li>    </a>
              <a href="/blog">       <li className="hover:text-custom-cyan">Blog</li>     </a>
              <a href="/faq">       <li className="hover:text-custom-cyan">FAQ</li>      </a>
              <a href="/contact">   <li className="hover:text-custom-cyan">Contact</li>  </a>
            </ul>
          ) : null}

        </div>

        {/* SCREEN */}
        <div className="z-50 bg-custom-blue-200 hidden fixed md:flex justify-between w-full px-5 py-4">
          <div className="flex gap-2 items-start">
            <i className="bg-blue-400 text-white rounded-full p-2 text-xl"><IoHomeOutline /></i>
            <h2 className='text-xl flex font-semibold pt-1 text-white'>Finloans</h2>
          </div>
          <ul className="flex gap-16 text-white pt-3">
            <a href="/">         <li className="hover:text-custom-cyan">Home</li>     </a>
            <a href="/loan">      <li className="hover:text-custom-cyan">Loan</li>     </a>
            <a href="/about">     <li className="hover:text-custom-cyan">About</li>    </a>
            <a href="/cages">          <li className="hover:text-custom-cyan">Pages</li>    </a>
            <a href="/blog">       <li className="hover:text-custom-cyan">Blog</li>     </a>
            <a href="/faq">       <li className="hover:text-custom-cyan">FAQ</li>      </a>
            <a href="/contact">   <li className="hover:text-custom-cyan">Contact</li>  </a>
          </ul>
          <main className='flex justify-center gap-5'>
            <span className="flex pt-2 text-white">+9126196754</span>
            <button className=' hover:bg-custom-cyan px-5 w-full bg-transparent duration-1000 hover:text-white hover:border hover:border-custom-cyan text-lg text-custom-cyan py-1 font-medium rounded-md border'>Apply for a loan</button>
          </main>
        </div>


        {children}
      </body>
    </html>
  );
}
